name: build

on: [push, pull_request]
#  push:
#    paths-ignore:
#      - 'README.md'
#      - 'docs/**'
#      - 'examples/**'
#      - '.dev_scripts/**'
#
#  pull_request:
#    paths-ignore:
#      - 'README.md'
#      - 'docs/**'
#      - 'examples/**'
#      - '.dev_scripts/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-2022]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Install ZJUTCV
      run: pip install -e .
    - name: Validate the installation
      run: python -c "import zjutcv"
    - name: Run unit tests
      run: pytest tests/
